version: '3.8'

services:
  sequence-report:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sequence-report
    image: dharshiniradhakrishnan/sequence-report:v0.1
    restart: unless-stopped

    environment:
      - THINGSBOARD_HOST=yantra24x7.cloud
      - THINGSBOARD_PORT=1884
      - THINGSBOARD_USER=pms@gmail.com
      - THINGSBOARD_PASSWORD=pmspms
      - THINGSBOARD_REST_URL=http://yantra24x7.cloud:8080
      - MQTT_BROKER=mqtt://yantra24x7.cloud:1884
      - MQTT_TOPIC=sequence_report
      - CUSTOMER_ID=ca71d920-4d2a-11f1-9352-592ed2a7210c
      - CUSTOMER_NAME=Surin
      - UPDATE_INTERVAL_SECONDS=120
      - TELEMETRY_LOOKBACK_HOURS=24
      - REPORTS_PORT=6016
      - NODE_ENV=development

    ports:
      - "6016:6016"
